name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      WOL_PORT: ${{ secrets.WOL_PORT }}
      ENCODED_TARGETS: ${{ secrets.ENCODED_TARGETS }}

    steps:
    - name: Check if WOL_PORT is set
      run: |
        if [ -z "$WOL_PORT" ]; then
          echo "WOL_PORT is not set. Aborting the workflow."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to your desired Node.js version

    - name: Install dependencies
      run: npm install

    # - name: Build and test
    #   run: npm test  # Replace with your build and test command

    - name: Deploy
      run: |
        # Clone the repository on the target machine (GitHub Actions runner)
        git clone https://github.com/natts-org/WoL_Service
        
        # Change to your app's directory
        cd WoL_Service

        echo $ENCODED_TARGETS | base64 -d > targets.json

        # Copy the service file to the appropriate location
        sudo cp wol.service /etc/systemd/system/  # Use 'sudo' to copy to system directory

        # Reload systemd to pick up the new service file
        sudo systemctl daemon-reload

        # Enable and start the service
        sudo systemctl enable wol.service
        sudo systemctl start wol.service
